= Effective testing for Quarkus applications
2021-10-21

✓ Test principles & constraints
  - execute fast, provide fast feedback
    code level tests, per hundreds < 1s
    integrative system test, per test ideally < 1s
  - fast development feedback, no startup costs between test runs, turnaround time < 5s
  - ability to refactor production code without significant test refactoring effort
  - changes in functional behavior should only result in minimal test code changes
  - ability to craft proper abstraction layers / delegation, tailed to domain
  - ability to support hot-reload development modes
  - compatibility with running & configuring test environment individually
  - reusability of test components (technical & functional) for multiple scenarios
✓ Test scopes
  code-level unit tests, use case tests, component tests, code-level integration tests, system / acceptance tests
✓ Code-level tests
  unit tests, JUnit, AssertJ, Mockito
✓ Use case tests, component tests
✓ Quarkus Continuous Testing
  `mvn quarkus:dev -Dquarkus.test.include-pattern='*MySpecialTest'`
  `mvn quarkus:dev -Dquarkus.test.exclude-pattern=''`
✓ Code-level integration tests
  `mvn test-compile failsafe:integration-test failsafe:verify`
✓ @QuarkusTest yes or no?
✓ System / acceptance tests
  (mis)using Quarkus for non-Quarkus projects
  https://blog.sebastian-daschner.com/entries/quarkus-dev-for-java-projects
✓ Effective testing workflows
  https://blog.sebastian-daschner.com/entries/quarkus-remote-dev-in-containers-update
✓ Local development, IDEs, build tooling, Maven, Gradle
  Testcontainers
✓ Databases & test data
✓ Data migration
✓ CI/CD pipelines and testing
✓ Test code quality & maintainable tests
  Abstraction, Delegation
  Tip: top-down approach if possible
✓ JVM test frameworks
✓ AssertJ custom assertions
✓ UI tests, Selenium, Selenide
✓ Test coverage, Jacoco
  Jacoco JVM Agent
✓ Advanced topics: Mutation testing, performance testing
  https://blog.sebastian-daschner.com/entries/complex-project-setups-testcontainers
  https://blog.sebastian-daschner.com/entries/microprofile-config-plain-java
✓ Books:
  Domain-Driven Design
  Clean Code

== Running the examples

You run the environment, containing the _coffee-shop_, _barista_ applications and the _coffee-shop-db_ using Docker containers with the provided scripts.

In order to run the Docker containers locally, you need to create a Docker network first: + 
`docker network create --subnet=192.168.42.0/24 dkrnet`
